spring:
  application:
    name: animal-adoption-api

  config:
    import: "optional:file:./.env[.properties]"

  datasource:
    url: "jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false